# Uncomment this line to define a global platform for your project
platform :ios, "6.0"

xcodeproj 'MBInfiniteScrollCollectionViewDemo'
workspace 'MBInfiniteScrollCollectionViewDemo'

pod 'MBInfiniteScrollCollectionView', :path => '..'
